### ISSUE TITLE
rpc: request block data through IPLD

### ISSUE THREAD

**Issue by marbar3778** [celestiaorg/lazyledger-core#189]
## Summary

As the migration to DA proofs begins the question arises on how to retrieve the required data when a user requests it via the RPC.

## Problem Definition

LL-core does not store the block data, it must request the user requested data from the IPLD plugin.

## Proposal

Define an interface within the IPLD plugin that is passed into the RPC layer. This interface should define getting block data. 

The rpc layer will need to use both the local storage (ll-core) and IPLD plugin to get the requested info. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by liamsi** [comment]
Now that validators and full node all store the data this will be easier: the nodes will all have the data locally and can reply just as before. Only difference might be that the data ist store (locally) in the ipfs data store instead of the tendermint store.
