### ISSUE TITLE
blockchain: propagate headers & DAHeaders

### ISSUE THREAD

**Issue by marbar3778** [celestiaorg/lazyledger-core#191]
## Summary

LL-core propagates blocks for fast sync, this is not possible anymore as the tendermint node will not be storing the blocks. 

## Proposal

Change the blockchain reactor to propagate Headers & DAHeaders instead of blocks.

**Comment by liamsi** [comment]
We decided to go with a more tendermint-as-a-balckbox approach for a first dev-net. Let's close this issue for now.
