### ISSUE TITLE
Move and refactor the `PutBlock` method

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/lazyledger-core#196]
The `PutBlock` method was introduced as a method to `Block` in #178. Having `PutBlock` where it is now adds network dependencies to the `types` package, which is undesirable. The original thinking in doing so was so that erasured data could be cached instead of recomputed. While caching the erasured data is still a good idea, it was not implemented in #178 and does not necessarily require `PutBlock` being a method to `Block`. 

We should probably make `PutBlock` a function and move it to a different package. This will require a general refactor, which includes exporting [the utility function](https://github.com/lazyledger/lazyledger-core/blob/76f8bf2182900144c73207070fdc81a68388a206/types/block.go#L318) shared by `PutBlock` and `fillDataAvailabilityHeader`.

As for where to move it, per a suggestion by @liamsi, I think we should move `PutBlock` and it's related code to `lazyledger-core/p2p/ipld`. 

ref: https://github.com/lazyledger/lazyledger-core/pull/178#discussion_r590672738

**Comment by evan-forbes** [comment]
relevant comment about the original API defined in #170 https://github.com/lazyledger/lazyledger-core/pull/178#discussion_r591337075

While `PutLeaves` was not implemented in #178, I think it should be added when we move `PutBlock`

**Comment by evan-forbes** [comment]
[this code](https://github.com/lazyledger/lazyledger-core/pull/178#discussion_r591357169) will also have to be moved and consolidated with `PutBlock`

**Comment by evan-forbes** [comment]
I'm linking this [comment](https://github.com/lazyledger/lazyledger-core/pull/178#discussion_r594635526) to remind myself to also include the suggested change into the refactor/move of `PutBlock`

**Comment by evan-forbes** [comment]
Another self reminder, wrap [this error](https://github.com/lazyledger/lazyledger-core/blob/5b848cb2a6efdb4d120235adb586cf88a59817c4/types/block_test.go#L1383)

**Comment by evan-forbes** [comment]
More notes:
As pointed out by @Wondertan, it's intuitive to think that calling `PutBlock` would also fill the data availability header, but this is not the case. In the implementation, filling the DAH and saving the block data to IPFS should be separate, but perhaps `PutBlock` could could also do this if not done already.

Somewhat unrelated, in #304, we're moving the ipfs API object to the block store in order to retrieve block data, and maybe we can move the `PutBlock` method their too.

**Comment by evan-forbes** [comment]
I think we can now close this issue now that #334 is merged. Any other opinions?

**Comment by Wondertan** [comment]
I think we can close this once PutBlock starts to return DAHeader

**Comment by evan-forbes** [comment]
So we just need to fill the DAH of the passed in `Block` if not done so already? Is the goal of this to not fill the DAH twice? If so, should we also disable filling the DAH when filling the `Header`?

**Comment by Wondertan** [comment]
> So we just need to fill the DAH of the passed in *Block if not done so already?
Ideally, I would change the interface to receive just types.Data bc that's the only thing used in PutBlock. 

> Is the goal of this to not fill the DAH twice?
Yeah, not to fill and recompute it twice

> If so, should we also disable filling the DAH when filling the Header?
Idk yet

**Comment by Wondertan** [comment]
@evan-forbes, is it closed?

**Comment by liamsi** [comment]
Yes, thanks @Wondertan 🙏🏼 I'm sure we can further improve the package structure a bit (similar to changes you started in #427) but the suggestions made here are already implemented.
