### ISSUE TITLE
Optimize RetrieveBlockData

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/lazyledger-core#278]
Currently, we spin up a go-rountine per row/colum leaf that we want to sample in `RetrieveBlockData`. It might be more efficient (and more readable) to use the IPFS api for this. 
Original discussion: https://github.com/lazyledger/lazyledger-core/pull/232#discussion_r609417214

Also related: #357

**Comment by Wondertan** [comment]
@liamsi, can we close this in favour of https://github.com/celestiaorg/lazyledger-core/issues/429

**Comment by liamsi** [comment]
OK, there is certainly more context in #429 already.
