### ISSUE TITLE
Implement ability to easily create merkle proofs from one share to the data hash

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/lazyledger-core#460]
## Summary

In order to create bad encoding fraud proofs, we need to have the ability to create a single merkle proof for a given share in the available data square.

## Details

Since we use `nmt` to create the row and column roots of the data availability header, and then a simple merkle tree of the row and column roots to create the data hash, this will require creating two proofs and adding them together. The first proof will come from `nmt`, and then second will be created using tendermint's [merkle](https://github.com/celestiaorg/lazyledger-core/tree/master/crypto/merkle) tree

### Action Items
- [ ] Implement the ability to combine merkle proofs from `nmt` and tendermint's [merkle](https://github.com/celestiaorg/lazyledger-core/tree/master/crypto/merkle) package

### References

tracking issue #459

**Comment by nusret1996** [comment]
Given the model for the light clients, we don't need the Merkle proof from the row/column roots to the availableDataRoot as the light clients are assumed to have the [availableDataHeader](https://github.com/celestiaorg/celestia-specs/blob/baa9eccb87b3aef434b9c56d55362720e096e173/src/specs/data_structures.md#availabledataheader). Thus, we will only need the first proof that will come from the NMT.

**Comment by evan-forbes** [comment]
Nice, thanks for updating. I think we can close this issue then

**Comment by liamsi** [comment]
There is still some work to be done here. I don't think that part is explicitly used in our code base:
> Thus, we will only need the first proof that will come from the NMT.

This proof is currently only implicitly given when downloading the data via ipfs. But in fact, this should be used throughout the code-base (e.g. when querying for Txs using rpc). I'm at least not sure if this is already the case.
